server:
  port: 8080
  host: 0.0.0.0
email:
  smtpUser: example@outlook.com
  smtpPswd: P@ssw0rd
  smtpServer: smtp-mail.outlook.com
  smtpPort: 587
task:
  taskName: Default Task
  cronTime: '30 17 * * *'
user:
  userName: Admin
  passWord: Admin